spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]'
            allowedOrigns: "http://localhost:8080"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
            allowedHeaders:
              - Content-Type
        add-to-simple-url-handler-mapping: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: USER-COURSES
          uri: lb://USER-COURSES
          predicates:
            - Path=/user-courses/**
            - Method=GET, POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: CART
          uri: lb://CART
          predicates:
            - Path=/cart/**
            - Method=GET, POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: COURSES
          uri: lb://COURSES
          predicates:
            - Path=/courses/**
            - Method=GET, POST, PUT, DELETE
          filters:
            - RemoveRequestHeader=Cookie
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
  instance:
    hostname: localhost
  enabled: true
